//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_table
    {
        public int appl_id { get; set; }
        public string job_desc { get; set; }
        public string min_qualification { get; set; }
        public string pref_qualification { get; set; }
        public string resp { get; set; }
        public Nullable<int> req_id { get; set; }
        public string appstatus { get; set; }
        public string manager_name { get; set; }
        public string project_name { get; set; }
        public Nullable<int> period_month { get; set; }
        public Nullable<int> noof_vacancies { get; set; }
        public string skill { get; set; }
        public string pgm_languages { get; set; }
        public Nullable<int> exp_years { get; set; }
        public string desg { get; set; }
        public Nullable<System.DateTime> dateapp { get; set; }
    
        public virtual request_table request_table { get; set; }
    }
}
