//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hiredcandidate_table
    {
        public int cand_id { get; set; }
        public string cand_name { get; set; }
        public string skills { get; set; }
        public string pgm_language { get; set; }
        public string high_qualification { get; set; }
        public string college { get; set; }
        public string university { get; set; }
        public string address { get; set; }
        public Nullable<int> exp_years { get; set; }
        public Nullable<int> notice_months { get; set; }
        public string latest_company { get; set; }
        public string latest_desg { get; set; }
        public Nullable<int> curr_sal { get; set; }
        public Nullable<System.DateTime> reg_date { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public Nullable<System.DateTime> hired_date { get; set; }
        public Nullable<System.DateTime> doj { get; set; }
        public Nullable<System.DateTime> appt_sent { get; set; }
        public Nullable<System.DateTime> appt_confirm { get; set; }
        public Nullable<int> req_id { get; set; }
        public string cand_email { get; set; }
    
        public virtual request_table request_table { get; set; }
    }
}
